version: '3'

services:
  clusters-ex-api:
    build: .
    image: clusters-ex-tools
    container_name: clusters-ex-tools
    restart: unless-stopped
    environment:
      - TZ=Asia/Taipei
    ports:
      - 8000:8000
    command: "uvicorn main:app --host 0.0.0.0 --port 8000"